name: Front-end Developer ~ Mat Hayward
author: Mat Hayward
markdown: redcarpet
pygments: true
permalink: /:title
exclude: [assets, config.rb, README.md]
strapline: Nottingham&rsquo;s answer to a question nobody asked.
baseurl: http://mathayward.com